name: Build_and_Deploy_Book

on:
    push:
        branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U -r requirements.txt
    - name: Build book
      run: |
        ./build.sh
    - name: Deploy book
      run: |
        ./deploy.sh